{% set name = "mambular" %}
{% set version = "1.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/basf/mamba-tabular/archive/v{{ version }}.tar.gz
  sha256: 16008babc99b6cf05cf1ba7e8848e999bdbde080ef6ee78a2d64808f63081e95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - poetry-core
  run:
    - pretab >=0.0.1,<0.0.2
    - accelerate >=1.2.1,<2.0.0
    - einops >=0.8.0,<0.9.0
    - scikit-optimize >=0.10.2,<0.11.0
    - scipy >=1.15.0,<2.0.0
    - python >={{ python_min }},<3.12.4a0
    - numpy <=1.26.4
    - pandas >=2.0.3,<3.0.0
    - lightning >=2.3.3,<3.0.0
    - scikit-learn >=1.3.2,<2.0.0
    - pytorch >=2.2.2,<=2.5.1
    - torchmetrics >=1.5.2,<2.0.0
    - setuptools >=75.3.0,<76.0.0
    - properscoring >=0.1.0,<0.2.0

test:
  imports:
    - mambular
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/basf/mamba-tabular
  summary: A python package for tabular deep learning with mamba blocks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
