{% set name = "mambular" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/basf/mamba-tabular/archive/v{{ version }}.tar.gz
  sha256: 631b95e84699abcc0e7c49173263192c2efcd79d2eb4bb382424ffa2784e92a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <=3.12.3,>=3.6
    - setuptools
    - pip
  run:
    - scikit-optimize
    - python <=3.12.3,>=3.6
    - numpy <=1.26.4
    - pandas
    - lightning
    - scikit-learn
    - pytorch
    - torchmetrics
    - setuptools
    - properscoring

test:
  imports:
    - mambular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/basf/mamba-tabular
  summary: A python package for tabular deep learning with mamba blocks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
